In [12]:
import numpy as np

In [13]:
x = np.array(([[0,0,0],[0,0,1],[0,1,0],\
             [0,1,1],[1,0,0],[1,0,1],[1,1,1]]), dtype = float)

In [14]:
y = np.array(([[1],[0],[0],[0,], \
               [0],[0],[1]]), dtype = float)

In [15]:
xPred = np.array(([0,0,1]), dtype=float)
x = x/np.amax(x, axis=0)
xPred = xPred/np.amax(xPred, axis=0) 

In [16]:
lossfile = open("SumSquaredLossList.csv","w")

In [19]:
class Neural_Network(object):
    def __init__(self):
        self.inputLayerSize =3
        self.outputLayerSize=1
        self.hiddenLayerSize=4
        self.W1 = np.random.randn(self.inputLayerSize, self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize, self.outputLayerSize)

    def feedForward(self,x):
        self.z = np.dot(x, self.W1)
        self.z2 = self.activationSigmoid(self.z)
        self.z3 = np.dot(self.z2, self.W2)
        o = self.activationSigmoid(self.z3)
        return o

    def backwardPropogate(self,x,y,o):
        self.o_error=y-o
        self.o_delta = self.o_error* self.activationSigmoidPrime(o)
        self.z2_error = self.o_delta.dot(self.W2.T)
        self.z2_delta = self.z2_error*self.activationSigmoidPrime(self.z2)
        self.W1 += x.T.dot(self.z2_delta)
        self.W2 += self.z2.T.dot(self.o_delta)

    def trainNetwork(self, x, y):
        o = self.feedForward(x)
        self.backwardPropogate(x,y,o)

    def activationSigmoid(self, s):
        return 1/(1 + np.exp(-s))

    def activationSigmoidPrime(self, s):
        return s*(1-s)

    def saveSumSquaredLossList(self,i, error):
        lossFile.write(str(i)+","+str(error.tolist())+ "\n")

    def saveWeights(self):
        np.savetxt("weightsLayer1.txt",self.W1,fmt="%s")
        np.savetxt("weightsLayer2.txt",self.W2, fmt="%s")

    def predictOutput(self):
        print("Predicted xor o/p data based on trained weights: ")
        print("Expected (x1-x3): \n" + str(xPred))
        print("Output (Y1): \n" + str(self.feedForward(xPred)))

myNeuralNetwork = Neural_Network()
trainingEpochs = 1000


In [21]:
for i in range(trainingEpochs):
    print("Epoch #"+ str(i)+"\n")
    print("network Input: \n" + str(x))
    print("Expected output : \n" + str(y))
    print("Actual Output: \n" + str(myNeuralNetwork.feedForward(x)))
    Loss = np.mean(np.square(y - myNeuralNetwork.feedForward(x)))
    print("Sum Squared Loss: \n" + str(Loss))
    print("\n")
    myNeuralNetwork.trainNetwork(x,y)
myNeuralNetwork.saveWeight()
myNeuralNetwork.predictOutput()

Epoch #0

network Input: 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 1.]]
Expected output : 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output: 
[[0.21143818]
 [0.16332241]
 [0.17157387]
 [0.1350527 ]
 [0.24376782]
 [0.18824079]
 [0.16608393]]
Sum Squared Loss: 
0.21235059123305003


Epoch #1

network Input: 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 1.]]
Expected output : 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output: 
[[0.23212451]
 [0.18389332]
 [0.19628515]
 [0.15890712]
 [0.27185069]
 [0.21572524]
 [0.19718929]]
Sum Squared Loss: 
0.20745343915140815


Epoch #2

network Input: 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 1.]]
Expected output : 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output: 
[[0.25060767]
 [0.20243293]
 [0.21987351]
 [0.18201666]
 [0.29691991]
 [0.24057437]
 [0.2271669 ]]
Sum Squared Loss: 
0.2039072638628477


Epoch #3

netw

AttributeError: 'Neural_Network' object has no attribute 'saveWeight'